---
title: "Initial Korean covid 19"
author: "Anicia Friend"
date: "2025-05-08"
output: 
  html_document: default
  pdf_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(digits=2)
require(tidyverse)
require(tigerstats)
require(lubridate)
require(knitr)
data <- read.csv(file="https://onlinestatbook.com/case_studies_rvls/physical_strength/data.txt",sep="",header=TRUE)  
```

### Model1: SIMS~ARM

```{r}
basiccNN<- ggplot(data,aes(y=SIMS,x=ARM))
```


```{r}
basiccNN +geom_point()  +ggtitle("SIMS vs ARM")
```

The scatterplot of SIMS versus ARM shows an upward trend, indicating that as ARM increases, SIMS tends to increase as well.  

### Numerical Results

```{r}
cor(SIMS~ARM,data=data)
```

### Inferential Results

```{r}
model1<- lm(SIMS~ARM,data=data)
summary.lm(model1)
```

### Target Dataframe

```{r}
target<-data.frame(ARM=90,GRIP=90)
```

```{r}
predict(model1,target,interval=c("prediction"))
```


```{r}
predict(model1,target,interval=c("confidence"))
```





